apiVersion : v1
kind : Service
metadata :
  name : smart-diet-service
spec :
  selector : 
    app : smart-diet
  ports :
    - protocol : TCP
      port: 80
      targetPort : 8080
      nodePort: 30491
  type : NodePort